// Code generated by protoc-gen-go-ttrpc. DO NOT EDIT.
// source: github.com/spin-stack/spinbox/api/spinbox/services/bundle/v1/bundle.proto
package bundle

import (
	context "context"
	ttrpc "github.com/containerd/ttrpc"
)

type TTRPCBundleServiceService interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
}

func RegisterTTRPCBundleServiceService(srv *ttrpc.Server, svc TTRPCBundleServiceService) {
	srv.RegisterService("spinbox.services.bundle.v1.BundleService", &ttrpc.ServiceDesc{
		Methods: map[string]ttrpc.Method{
			"Create": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req CreateRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.Create(ctx, &req)
			},
		},
	})
}

type ttrpcbundleserviceClient struct {
	client *ttrpc.Client
}

func NewTTRPCBundleServiceClient(client *ttrpc.Client) TTRPCBundleServiceService {
	return &ttrpcbundleserviceClient{
		client: client,
	}
}

func (c *ttrpcbundleserviceClient) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	var resp CreateResponse
	if err := c.client.Call(ctx, "spinbox.services.bundle.v1.BundleService", "Create", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
