// Code generated by protoc-gen-go-ttrpc. DO NOT EDIT.
// source: github.com/spin-stack/spinbox/api/spinbox/services/stdio/v1/stdio.proto
package stdio

import (
	context "context"
	ttrpc "github.com/containerd/ttrpc"
)

type TTRPCStdIOServiceService interface {
	WriteStdin(context.Context, *WriteStdinRequest) (*WriteStdinResponse, error)
	ReadStdout(context.Context, *ReadStdoutRequest, TTRPCStdIOService_ReadStdoutServer) error
	ReadStderr(context.Context, *ReadStderrRequest, TTRPCStdIOService_ReadStderrServer) error
	CloseStdin(context.Context, *CloseStdinRequest) (*CloseStdinResponse, error)
}

type TTRPCStdIOService_ReadStdoutServer interface {
	Send(*ReadStdoutResponse) error
	ttrpc.StreamServer
}

type ttrpcstdioserviceReadStdoutServer struct {
	ttrpc.StreamServer
}

func (x *ttrpcstdioserviceReadStdoutServer) Send(m *ReadStdoutResponse) error {
	return x.StreamServer.SendMsg(m)
}

type TTRPCStdIOService_ReadStderrServer interface {
	Send(*ReadStderrResponse) error
	ttrpc.StreamServer
}

type ttrpcstdioserviceReadStderrServer struct {
	ttrpc.StreamServer
}

func (x *ttrpcstdioserviceReadStderrServer) Send(m *ReadStderrResponse) error {
	return x.StreamServer.SendMsg(m)
}

func RegisterTTRPCStdIOServiceService(srv *ttrpc.Server, svc TTRPCStdIOServiceService) {
	srv.RegisterService("spinbox.services.stdio.v1.StdIOService", &ttrpc.ServiceDesc{
		Methods: map[string]ttrpc.Method{
			"WriteStdin": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req WriteStdinRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.WriteStdin(ctx, &req)
			},
			"CloseStdin": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req CloseStdinRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.CloseStdin(ctx, &req)
			},
		},
		Streams: map[string]ttrpc.Stream{
			"ReadStdout": {
				Handler: func(ctx context.Context, stream ttrpc.StreamServer) (interface{}, error) {
					m := new(ReadStdoutRequest)
					if err := stream.RecvMsg(m); err != nil {
						return nil, err
					}
					return nil, svc.ReadStdout(ctx, m, &ttrpcstdioserviceReadStdoutServer{stream})
				},
				StreamingClient: false,
				StreamingServer: true,
			},
			"ReadStderr": {
				Handler: func(ctx context.Context, stream ttrpc.StreamServer) (interface{}, error) {
					m := new(ReadStderrRequest)
					if err := stream.RecvMsg(m); err != nil {
						return nil, err
					}
					return nil, svc.ReadStderr(ctx, m, &ttrpcstdioserviceReadStderrServer{stream})
				},
				StreamingClient: false,
				StreamingServer: true,
			},
		},
	})
}

type TTRPCStdIOServiceClient interface {
	WriteStdin(context.Context, *WriteStdinRequest) (*WriteStdinResponse, error)
	ReadStdout(context.Context, *ReadStdoutRequest) (TTRPCStdIOService_ReadStdoutClient, error)
	ReadStderr(context.Context, *ReadStderrRequest) (TTRPCStdIOService_ReadStderrClient, error)
	CloseStdin(context.Context, *CloseStdinRequest) (*CloseStdinResponse, error)
}

type ttrpcstdioserviceClient struct {
	client *ttrpc.Client
}

func NewTTRPCStdIOServiceClient(client *ttrpc.Client) TTRPCStdIOServiceClient {
	return &ttrpcstdioserviceClient{
		client: client,
	}
}

func (c *ttrpcstdioserviceClient) WriteStdin(ctx context.Context, req *WriteStdinRequest) (*WriteStdinResponse, error) {
	var resp WriteStdinResponse
	if err := c.client.Call(ctx, "spinbox.services.stdio.v1.StdIOService", "WriteStdin", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpcstdioserviceClient) ReadStdout(ctx context.Context, req *ReadStdoutRequest) (TTRPCStdIOService_ReadStdoutClient, error) {
	stream, err := c.client.NewStream(ctx, &ttrpc.StreamDesc{
		StreamingClient: false,
		StreamingServer: true,
	}, "spinbox.services.stdio.v1.StdIOService", "ReadStdout", req)
	if err != nil {
		return nil, err
	}
	x := &ttrpcstdioserviceReadStdoutClient{stream}
	return x, nil
}

type TTRPCStdIOService_ReadStdoutClient interface {
	Recv() (*ReadStdoutResponse, error)
	ttrpc.ClientStream
}

type ttrpcstdioserviceReadStdoutClient struct {
	ttrpc.ClientStream
}

func (x *ttrpcstdioserviceReadStdoutClient) Recv() (*ReadStdoutResponse, error) {
	m := new(ReadStdoutResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ttrpcstdioserviceClient) ReadStderr(ctx context.Context, req *ReadStderrRequest) (TTRPCStdIOService_ReadStderrClient, error) {
	stream, err := c.client.NewStream(ctx, &ttrpc.StreamDesc{
		StreamingClient: false,
		StreamingServer: true,
	}, "spinbox.services.stdio.v1.StdIOService", "ReadStderr", req)
	if err != nil {
		return nil, err
	}
	x := &ttrpcstdioserviceReadStderrClient{stream}
	return x, nil
}

type TTRPCStdIOService_ReadStderrClient interface {
	Recv() (*ReadStderrResponse, error)
	ttrpc.ClientStream
}

type ttrpcstdioserviceReadStderrClient struct {
	ttrpc.ClientStream
}

func (x *ttrpcstdioserviceReadStderrClient) Recv() (*ReadStderrResponse, error) {
	m := new(ReadStderrResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ttrpcstdioserviceClient) CloseStdin(ctx context.Context, req *CloseStdinRequest) (*CloseStdinResponse, error) {
	var resp CloseStdinResponse
	if err := c.client.Call(ctx, "spinbox.services.stdio.v1.StdIOService", "CloseStdin", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
