// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.1
// source: github.com/spin-stack/spinbox/api/spinbox/services/system/v1/info.proto

package system

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_rawDescGZIP(), []int{0}
}

type InfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// version is the spinbox vminitd version (e.g., "1.0.0").
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// kernel_version is the Linux kernel version running in the VM (e.g., "6.1.0").
	KernelVersion string `protobuf:"bytes,2,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_rawDescGZIP(), []int{1}
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

type PrepareShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareShutdownRequest) Reset() {
	*x = PrepareShutdownRequest{}
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareShutdownRequest) ProtoMessage() {}

func (x *PrepareShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareShutdownRequest.ProtoReflect.Descriptor instead.
func (*PrepareShutdownRequest) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_rawDescGZIP(), []int{2}
}

type PrepareShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareShutdownResponse) Reset() {
	*x = PrepareShutdownResponse{}
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareShutdownResponse) ProtoMessage() {}

func (x *PrepareShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareShutdownResponse.ProtoReflect.Descriptor instead.
func (*PrepareShutdownResponse) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_rawDescGZIP(), []int{3}
}

type FreezeFilesystemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreezeFilesystemsRequest) Reset() {
	*x = FreezeFilesystemsRequest{}
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreezeFilesystemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreezeFilesystemsRequest) ProtoMessage() {}

func (x *FreezeFilesystemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreezeFilesystemsRequest.ProtoReflect.Descriptor instead.
func (*FreezeFilesystemsRequest) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_rawDescGZIP(), []int{4}
}

type FreezeFilesystemsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// frozen lists the mount points that were frozen by this call.
	Frozen        []string `protobuf:"bytes,1,rep,name=frozen,proto3" json:"frozen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreezeFilesystemsResponse) Reset() {
	*x = FreezeFilesystemsResponse{}
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreezeFilesystemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreezeFilesystemsResponse) ProtoMessage() {}

func (x *FreezeFilesystemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreezeFilesystemsResponse.ProtoReflect.Descriptor instead.
func (*FreezeFilesystemsResponse) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_rawDescGZIP(), []int{5}
}

func (x *FreezeFilesystemsResponse) GetFrozen() []string {
	if x != nil {
		return x.Frozen
	}
	return nil
}

type ThawFilesystemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThawFilesystemsRequest) Reset() {
	*x = ThawFilesystemsRequest{}
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThawFilesystemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThawFilesystemsRequest) ProtoMessage() {}

func (x *ThawFilesystemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThawFilesystemsRequest.ProtoReflect.Descriptor instead.
func (*ThawFilesystemsRequest) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_rawDescGZIP(), []int{6}
}

type ThawFilesystemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThawFilesystemsResponse) Reset() {
	*x = ThawFilesystemsResponse{}
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThawFilesystemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThawFilesystemsResponse) ProtoMessage() {}

func (x *ThawFilesystemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThawFilesystemsResponse.ProtoReflect.Descriptor instead.
func (*ThawFilesystemsResponse) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_rawDescGZIP(), []int{7}
}

type OfflineCPURequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cpu_id is the logical CPU ID to offline (zero-indexed, e.g., 0, 1, 2).
	// This corresponds to /sys/devices/system/cpu/cpu{N}.
	CpuID         uint32 `protobuf:"varint,1,opt,name=cpu_id,json=cpuId,proto3" json:"cpu_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfflineCPURequest) Reset() {
	*x = OfflineCPURequest{}
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflineCPURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineCPURequest) ProtoMessage() {}

func (x *OfflineCPURequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineCPURequest.ProtoReflect.Descriptor instead.
func (*OfflineCPURequest) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_rawDescGZIP(), []int{8}
}

func (x *OfflineCPURequest) GetCpuID() uint32 {
	if x != nil {
		return x.CpuID
	}
	return 0
}

type OfflineCPUResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfflineCPUResponse) Reset() {
	*x = OfflineCPUResponse{}
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflineCPUResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineCPUResponse) ProtoMessage() {}

func (x *OfflineCPUResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineCPUResponse.ProtoReflect.Descriptor instead.
func (*OfflineCPUResponse) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_rawDescGZIP(), []int{9}
}

type OnlineCPURequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cpu_id is the logical CPU ID to online (zero-indexed, e.g., 0, 1, 2).
	// This corresponds to /sys/devices/system/cpu/cpu{N}.
	CpuID         uint32 `protobuf:"varint,1,opt,name=cpu_id,json=cpuId,proto3" json:"cpu_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineCPURequest) Reset() {
	*x = OnlineCPURequest{}
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineCPURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineCPURequest) ProtoMessage() {}

func (x *OnlineCPURequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineCPURequest.ProtoReflect.Descriptor instead.
func (*OnlineCPURequest) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_rawDescGZIP(), []int{10}
}

func (x *OnlineCPURequest) GetCpuID() uint32 {
	if x != nil {
		return x.CpuID
	}
	return 0
}

type OnlineCPUResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineCPUResponse) Reset() {
	*x = OnlineCPUResponse{}
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineCPUResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineCPUResponse) ProtoMessage() {}

func (x *OnlineCPUResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineCPUResponse.ProtoReflect.Descriptor instead.
func (*OnlineCPUResponse) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_rawDescGZIP(), []int{11}
}

type RescanPCIRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// expected_block_devices is how many virtio block devices the host attached
	// to this VM. The guest waits for that many rather than for a timeout to
	// expire: it is told what to expect instead of guessing.
	ExpectedBlockDevices uint32 `protobuf:"varint,1,opt,name=expected_block_devices,json=expectedBlockDevices,proto3" json:"expected_block_devices,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RescanPCIRequest) Reset() {
	*x = RescanPCIRequest{}
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RescanPCIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RescanPCIRequest) ProtoMessage() {}

func (x *RescanPCIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RescanPCIRequest.ProtoReflect.Descriptor instead.
func (*RescanPCIRequest) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_rawDescGZIP(), []int{12}
}

func (x *RescanPCIRequest) GetExpectedBlockDevices() uint32 {
	if x != nil {
		return x.ExpectedBlockDevices
	}
	return 0
}

type RescanPCIResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// block_devices lists the virtio block device names found after the rescan
	// (e.g. "vda", "vdb").
	BlockDevices  []string `protobuf:"bytes,1,rep,name=block_devices,json=blockDevices,proto3" json:"block_devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RescanPCIResponse) Reset() {
	*x = RescanPCIResponse{}
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RescanPCIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RescanPCIResponse) ProtoMessage() {}

func (x *RescanPCIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RescanPCIResponse.ProtoReflect.Descriptor instead.
func (*RescanPCIResponse) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_rawDescGZIP(), []int{13}
}

func (x *RescanPCIResponse) GetBlockDevices() []string {
	if x != nil {
		return x.BlockDevices
	}
	return nil
}

type ConfigureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// network is this VM's address and routing. Absent leaves networking alone,
	// which is what a workload without a NIC wants.
	Network *NetworkConfig `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	// expected_block_devices is how many virtio block devices the host attached.
	// The guest triggers a PCI rescan and waits for that many: a restored VM
	// enumerated its bus inside the template, before these disks existed.
	ExpectedBlockDevices uint32 `protobuf:"varint,2,opt,name=expected_block_devices,json=expectedBlockDevices,proto3" json:"expected_block_devices,omitempty"`
	// extras_disk is the block device holding the extras archive (e.g. "/dev/vdb"),
	// empty when this container has none. It corresponds to what the boot path
	// derives from spin.extras_disk.
	ExtrasDisk string `protobuf:"bytes,3,opt,name=extras_disk,json=extrasDisk,proto3" json:"extras_disk,omitempty"`
	// restored says this VM was restored from a template rather than booted.
	//
	// Only the host knows. The guest cannot tell from the inside - that is the
	// whole point of a restore - and two things depend on it: its clock resumes
	// at the time the template was frozen, and its random pool is the template's
	// until the vmgenid device reseeds it. Both are corrected either way; this
	// says whether failing to is an error or the expected answer.
	Restored      bool `protobuf:"varint,4,opt,name=restored,proto3" json:"restored,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_rawDescGZIP(), []int{14}
}

func (x *ConfigureRequest) GetNetwork() *NetworkConfig {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *ConfigureRequest) GetExpectedBlockDevices() uint32 {
	if x != nil {
		return x.ExpectedBlockDevices
	}
	return 0
}

func (x *ConfigureRequest) GetExtrasDisk() string {
	if x != nil {
		return x.ExtrasDisk
	}
	return ""
}

func (x *ConfigureRequest) GetRestored() bool {
	if x != nil {
		return x.Restored
	}
	return false
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_rawDescGZIP(), []int{15}
}

type NetworkConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// device is the interface to configure. Empty means eth0, which is what the
	// kernel names the single virtio-net device under net.ifnames=0.
	Device string `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	// mac is the hardware address this VM should use.
	//
	// Unlike the vsock CID, a NIC's MAC *is* carried in the migration stream
	// (VMSTATE_UINT8_ARRAY(mac, VirtIONet, ETH_ALEN)), so a restored guest comes
	// up believing it is the template's NIC. Empty leaves it untouched.
	Mac string `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	// ip, netmask and gateway are this VM's address, in the same form the ip=
	// kernel parameter carries them.
	Ip      string `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Netmask string `protobuf:"bytes,4,opt,name=netmask,proto3" json:"netmask,omitempty"`
	Gateway string `protobuf:"bytes,5,opt,name=gateway,proto3" json:"gateway,omitempty"`
	// dns lists the nameservers to write to /etc/resolv.conf.
	Dns []string `protobuf:"bytes,6,rep,name=dns,proto3" json:"dns,omitempty"`
	// metadata_route asks for the host route to the metadata service via the
	// gateway. It corresponds to spin.metadata_addr on the boot path.
	MetadataRoute bool `protobuf:"varint,7,opt,name=metadata_route,json=metadataRoute,proto3" json:"metadata_route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkConfig) Reset() {
	*x = NetworkConfig{}
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfig) ProtoMessage() {}

func (x *NetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfig.ProtoReflect.Descriptor instead.
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_rawDescGZIP(), []int{16}
}

func (x *NetworkConfig) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *NetworkConfig) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *NetworkConfig) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *NetworkConfig) GetNetmask() string {
	if x != nil {
		return x.Netmask
	}
	return ""
}

func (x *NetworkConfig) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *NetworkConfig) GetDns() []string {
	if x != nil {
		return x.Dns
	}
	return nil
}

func (x *NetworkConfig) GetMetadataRoute() bool {
	if x != nil {
		return x.MetadataRoute
	}
	return false
}

var File_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto protoreflect.FileDescriptor

const file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_rawDesc = "" +
	"\n" +
	"Ggithub.com/spin-stack/spinbox/api/spinbox/services/system/v1/info.proto\x12\x1aspinbox.services.system.v1\"\r\n" +
	"\vInfoRequest\"O\n" +
	"\fInfoResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12%\n" +
	"\x0ekernel_version\x18\x02 \x01(\tR\rkernelVersion\"\x18\n" +
	"\x16PrepareShutdownRequest\"\x19\n" +
	"\x17PrepareShutdownResponse\"\x1a\n" +
	"\x18FreezeFilesystemsRequest\"3\n" +
	"\x19FreezeFilesystemsResponse\x12\x16\n" +
	"\x06frozen\x18\x01 \x03(\tR\x06frozen\"\x18\n" +
	"\x16ThawFilesystemsRequest\"\x19\n" +
	"\x17ThawFilesystemsResponse\"*\n" +
	"\x11OfflineCPURequest\x12\x15\n" +
	"\x06cpu_id\x18\x01 \x01(\rR\x05cpuId\"\x14\n" +
	"\x12OfflineCPUResponse\")\n" +
	"\x10OnlineCPURequest\x12\x15\n" +
	"\x06cpu_id\x18\x01 \x01(\rR\x05cpuId\"\x13\n" +
	"\x11OnlineCPUResponse\"H\n" +
	"\x10RescanPCIRequest\x124\n" +
	"\x16expected_block_devices\x18\x01 \x01(\rR\x14expectedBlockDevices\"8\n" +
	"\x11RescanPCIResponse\x12#\n" +
	"\rblock_devices\x18\x01 \x03(\tR\fblockDevices\"\xca\x01\n" +
	"\x10ConfigureRequest\x12C\n" +
	"\anetwork\x18\x01 \x01(\v2).spinbox.services.system.v1.NetworkConfigR\anetwork\x124\n" +
	"\x16expected_block_devices\x18\x02 \x01(\rR\x14expectedBlockDevices\x12\x1f\n" +
	"\vextras_disk\x18\x03 \x01(\tR\n" +
	"extrasDisk\x12\x1a\n" +
	"\brestored\x18\x04 \x01(\bR\brestored\"\x13\n" +
	"\x11ConfigureResponse\"\xb6\x01\n" +
	"\rNetworkConfig\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\tR\x03mac\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x18\n" +
	"\anetmask\x18\x04 \x01(\tR\anetmask\x12\x18\n" +
	"\agateway\x18\x05 \x01(\tR\agateway\x12\x10\n" +
	"\x03dns\x18\x06 \x03(\tR\x03dns\x12%\n" +
	"\x0emetadata_route\x18\a \x01(\bR\rmetadataRoute2\x90\a\n" +
	"\rSystemService\x12Y\n" +
	"\x04Info\x12'.spinbox.services.system.v1.InfoRequest\x1a(.spinbox.services.system.v1.InfoResponse\x12z\n" +
	"\x0fPrepareShutdown\x122.spinbox.services.system.v1.PrepareShutdownRequest\x1a3.spinbox.services.system.v1.PrepareShutdownResponse\x12\x80\x01\n" +
	"\x11FreezeFilesystems\x124.spinbox.services.system.v1.FreezeFilesystemsRequest\x1a5.spinbox.services.system.v1.FreezeFilesystemsResponse\x12z\n" +
	"\x0fThawFilesystems\x122.spinbox.services.system.v1.ThawFilesystemsRequest\x1a3.spinbox.services.system.v1.ThawFilesystemsResponse\x12k\n" +
	"\n" +
	"OfflineCPU\x12-.spinbox.services.system.v1.OfflineCPURequest\x1a..spinbox.services.system.v1.OfflineCPUResponse\x12h\n" +
	"\tOnlineCPU\x12,.spinbox.services.system.v1.OnlineCPURequest\x1a-.spinbox.services.system.v1.OnlineCPUResponse\x12h\n" +
	"\tRescanPCI\x12,.spinbox.services.system.v1.RescanPCIRequest\x1a-.spinbox.services.system.v1.RescanPCIResponse\x12h\n" +
	"\tConfigure\x12,.spinbox.services.system.v1.ConfigureRequest\x1a-.spinbox.services.system.v1.ConfigureResponseBEZCgithub.com/spin-stack/spinbox/api/spinbox/services/system/v1;systemb\x06proto3"

var (
	file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_rawDescOnce sync.Once
	file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_rawDescData []byte
)

func file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_rawDescGZIP() []byte {
	file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_rawDescOnce.Do(func() {
		file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_rawDesc), len(file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_rawDesc)))
	})
	return file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_rawDescData
}

var file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_goTypes = []any{
	(*InfoRequest)(nil),               // 0: spinbox.services.system.v1.InfoRequest
	(*InfoResponse)(nil),              // 1: spinbox.services.system.v1.InfoResponse
	(*PrepareShutdownRequest)(nil),    // 2: spinbox.services.system.v1.PrepareShutdownRequest
	(*PrepareShutdownResponse)(nil),   // 3: spinbox.services.system.v1.PrepareShutdownResponse
	(*FreezeFilesystemsRequest)(nil),  // 4: spinbox.services.system.v1.FreezeFilesystemsRequest
	(*FreezeFilesystemsResponse)(nil), // 5: spinbox.services.system.v1.FreezeFilesystemsResponse
	(*ThawFilesystemsRequest)(nil),    // 6: spinbox.services.system.v1.ThawFilesystemsRequest
	(*ThawFilesystemsResponse)(nil),   // 7: spinbox.services.system.v1.ThawFilesystemsResponse
	(*OfflineCPURequest)(nil),         // 8: spinbox.services.system.v1.OfflineCPURequest
	(*OfflineCPUResponse)(nil),        // 9: spinbox.services.system.v1.OfflineCPUResponse
	(*OnlineCPURequest)(nil),          // 10: spinbox.services.system.v1.OnlineCPURequest
	(*OnlineCPUResponse)(nil),         // 11: spinbox.services.system.v1.OnlineCPUResponse
	(*RescanPCIRequest)(nil),          // 12: spinbox.services.system.v1.RescanPCIRequest
	(*RescanPCIResponse)(nil),         // 13: spinbox.services.system.v1.RescanPCIResponse
	(*ConfigureRequest)(nil),          // 14: spinbox.services.system.v1.ConfigureRequest
	(*ConfigureResponse)(nil),         // 15: spinbox.services.system.v1.ConfigureResponse
	(*NetworkConfig)(nil),             // 16: spinbox.services.system.v1.NetworkConfig
}
var file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_depIdxs = []int32{
	16, // 0: spinbox.services.system.v1.ConfigureRequest.network:type_name -> spinbox.services.system.v1.NetworkConfig
	0,  // 1: spinbox.services.system.v1.SystemService.Info:input_type -> spinbox.services.system.v1.InfoRequest
	2,  // 2: spinbox.services.system.v1.SystemService.PrepareShutdown:input_type -> spinbox.services.system.v1.PrepareShutdownRequest
	4,  // 3: spinbox.services.system.v1.SystemService.FreezeFilesystems:input_type -> spinbox.services.system.v1.FreezeFilesystemsRequest
	6,  // 4: spinbox.services.system.v1.SystemService.ThawFilesystems:input_type -> spinbox.services.system.v1.ThawFilesystemsRequest
	8,  // 5: spinbox.services.system.v1.SystemService.OfflineCPU:input_type -> spinbox.services.system.v1.OfflineCPURequest
	10, // 6: spinbox.services.system.v1.SystemService.OnlineCPU:input_type -> spinbox.services.system.v1.OnlineCPURequest
	12, // 7: spinbox.services.system.v1.SystemService.RescanPCI:input_type -> spinbox.services.system.v1.RescanPCIRequest
	14, // 8: spinbox.services.system.v1.SystemService.Configure:input_type -> spinbox.services.system.v1.ConfigureRequest
	1,  // 9: spinbox.services.system.v1.SystemService.Info:output_type -> spinbox.services.system.v1.InfoResponse
	3,  // 10: spinbox.services.system.v1.SystemService.PrepareShutdown:output_type -> spinbox.services.system.v1.PrepareShutdownResponse
	5,  // 11: spinbox.services.system.v1.SystemService.FreezeFilesystems:output_type -> spinbox.services.system.v1.FreezeFilesystemsResponse
	7,  // 12: spinbox.services.system.v1.SystemService.ThawFilesystems:output_type -> spinbox.services.system.v1.ThawFilesystemsResponse
	9,  // 13: spinbox.services.system.v1.SystemService.OfflineCPU:output_type -> spinbox.services.system.v1.OfflineCPUResponse
	11, // 14: spinbox.services.system.v1.SystemService.OnlineCPU:output_type -> spinbox.services.system.v1.OnlineCPUResponse
	13, // 15: spinbox.services.system.v1.SystemService.RescanPCI:output_type -> spinbox.services.system.v1.RescanPCIResponse
	15, // 16: spinbox.services.system.v1.SystemService.Configure:output_type -> spinbox.services.system.v1.ConfigureResponse
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_init() }
func file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_init() {
	if File_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_rawDesc), len(file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_goTypes,
		DependencyIndexes: file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_depIdxs,
		MessageInfos:      file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_msgTypes,
	}.Build()
	File_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto = out.File
	file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_goTypes = nil
	file_github_com_spin_stack_spinbox_api_spinbox_services_system_v1_info_proto_depIdxs = nil
}
