// Code generated by protoc-gen-go-ttrpc. DO NOT EDIT.
// source: github.com/spin-stack/spinbox/api/spinbox/services/system/v1/info.proto
package system

import (
	context "context"
	ttrpc "github.com/containerd/ttrpc"
)

type TTRPCSystemServiceService interface {
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	PrepareShutdown(context.Context, *PrepareShutdownRequest) (*PrepareShutdownResponse, error)
	FreezeFilesystems(context.Context, *FreezeFilesystemsRequest) (*FreezeFilesystemsResponse, error)
	ThawFilesystems(context.Context, *ThawFilesystemsRequest) (*ThawFilesystemsResponse, error)
	OfflineCPU(context.Context, *OfflineCPURequest) (*OfflineCPUResponse, error)
	OnlineCPU(context.Context, *OnlineCPURequest) (*OnlineCPUResponse, error)
	RescanPCI(context.Context, *RescanPCIRequest) (*RescanPCIResponse, error)
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
}

func RegisterTTRPCSystemServiceService(srv *ttrpc.Server, svc TTRPCSystemServiceService) {
	srv.RegisterService("spinbox.services.system.v1.SystemService", &ttrpc.ServiceDesc{
		Methods: map[string]ttrpc.Method{
			"Info": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req InfoRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.Info(ctx, &req)
			},
			"PrepareShutdown": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req PrepareShutdownRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.PrepareShutdown(ctx, &req)
			},
			"FreezeFilesystems": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req FreezeFilesystemsRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.FreezeFilesystems(ctx, &req)
			},
			"ThawFilesystems": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req ThawFilesystemsRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.ThawFilesystems(ctx, &req)
			},
			"OfflineCPU": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req OfflineCPURequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.OfflineCPU(ctx, &req)
			},
			"OnlineCPU": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req OnlineCPURequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.OnlineCPU(ctx, &req)
			},
			"RescanPCI": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req RescanPCIRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.RescanPCI(ctx, &req)
			},
			"Configure": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req ConfigureRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.Configure(ctx, &req)
			},
		},
	})
}

type ttrpcsystemserviceClient struct {
	client *ttrpc.Client
}

func NewTTRPCSystemServiceClient(client *ttrpc.Client) TTRPCSystemServiceService {
	return &ttrpcsystemserviceClient{
		client: client,
	}
}

func (c *ttrpcsystemserviceClient) Info(ctx context.Context, req *InfoRequest) (*InfoResponse, error) {
	var resp InfoResponse
	if err := c.client.Call(ctx, "spinbox.services.system.v1.SystemService", "Info", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpcsystemserviceClient) PrepareShutdown(ctx context.Context, req *PrepareShutdownRequest) (*PrepareShutdownResponse, error) {
	var resp PrepareShutdownResponse
	if err := c.client.Call(ctx, "spinbox.services.system.v1.SystemService", "PrepareShutdown", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpcsystemserviceClient) FreezeFilesystems(ctx context.Context, req *FreezeFilesystemsRequest) (*FreezeFilesystemsResponse, error) {
	var resp FreezeFilesystemsResponse
	if err := c.client.Call(ctx, "spinbox.services.system.v1.SystemService", "FreezeFilesystems", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpcsystemserviceClient) ThawFilesystems(ctx context.Context, req *ThawFilesystemsRequest) (*ThawFilesystemsResponse, error) {
	var resp ThawFilesystemsResponse
	if err := c.client.Call(ctx, "spinbox.services.system.v1.SystemService", "ThawFilesystems", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpcsystemserviceClient) OfflineCPU(ctx context.Context, req *OfflineCPURequest) (*OfflineCPUResponse, error) {
	var resp OfflineCPUResponse
	if err := c.client.Call(ctx, "spinbox.services.system.v1.SystemService", "OfflineCPU", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpcsystemserviceClient) OnlineCPU(ctx context.Context, req *OnlineCPURequest) (*OnlineCPUResponse, error) {
	var resp OnlineCPUResponse
	if err := c.client.Call(ctx, "spinbox.services.system.v1.SystemService", "OnlineCPU", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpcsystemserviceClient) RescanPCI(ctx context.Context, req *RescanPCIRequest) (*RescanPCIResponse, error) {
	var resp RescanPCIResponse
	if err := c.client.Call(ctx, "spinbox.services.system.v1.SystemService", "RescanPCI", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpcsystemserviceClient) Configure(ctx context.Context, req *ConfigureRequest) (*ConfigureResponse, error) {
	var resp ConfigureResponse
	if err := c.client.Call(ctx, "spinbox.services.system.v1.SystemService", "Configure", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
