// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.1
// source: github.com/spin-stack/spinbox/api/spinbox/services/vmevents/v1/events.proto

package vmevents

import (
	types "github.com/containerd/containerd/api/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_vmevents_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_vmevents_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_spinbox_services_vmevents_v1_events_proto_rawDescGZIP(), []int{0}
}

type StreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// envelope is one containerd event, exactly as the guest published it.
	Envelope      *types.Envelope `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_vmevents_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_spinbox_services_vmevents_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_spinbox_services_vmevents_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *StreamResponse) GetEnvelope() *types.Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

var File_github_com_spin_stack_spinbox_api_spinbox_services_vmevents_v1_events_proto protoreflect.FileDescriptor

const file_github_com_spin_stack_spinbox_api_spinbox_services_vmevents_v1_events_proto_rawDesc = "" +
	"\n" +
	"Kgithub.com/spin-stack/spinbox/api/spinbox/services/vmevents/v1/events.proto\x12\x1cspinbox.services.vmevents.v1\x1a6github.com/containerd/containerd/api/types/event.proto\"\x0f\n" +
	"\rStreamRequest\"H\n" +
	"\x0eStreamResponse\x126\n" +
	"\benvelope\x18\x01 \x01(\v2\x1a.containerd.types.EnvelopeR\benvelope2v\n" +
	"\rEventsService\x12e\n" +
	"\x06Stream\x12+.spinbox.services.vmevents.v1.StreamRequest\x1a,.spinbox.services.vmevents.v1.StreamResponse0\x01BIZGgithub.com/spin-stack/spinbox/api/spinbox/services/vmevents/v1;vmeventsb\x06proto3"

var (
	file_github_com_spin_stack_spinbox_api_spinbox_services_vmevents_v1_events_proto_rawDescOnce sync.Once
	file_github_com_spin_stack_spinbox_api_spinbox_services_vmevents_v1_events_proto_rawDescData []byte
)

func file_github_com_spin_stack_spinbox_api_spinbox_services_vmevents_v1_events_proto_rawDescGZIP() []byte {
	file_github_com_spin_stack_spinbox_api_spinbox_services_vmevents_v1_events_proto_rawDescOnce.Do(func() {
		file_github_com_spin_stack_spinbox_api_spinbox_services_vmevents_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_spin_stack_spinbox_api_spinbox_services_vmevents_v1_events_proto_rawDesc), len(file_github_com_spin_stack_spinbox_api_spinbox_services_vmevents_v1_events_proto_rawDesc)))
	})
	return file_github_com_spin_stack_spinbox_api_spinbox_services_vmevents_v1_events_proto_rawDescData
}

var file_github_com_spin_stack_spinbox_api_spinbox_services_vmevents_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_spin_stack_spinbox_api_spinbox_services_vmevents_v1_events_proto_goTypes = []any{
	(*StreamRequest)(nil),  // 0: spinbox.services.vmevents.v1.StreamRequest
	(*StreamResponse)(nil), // 1: spinbox.services.vmevents.v1.StreamResponse
	(*types.Envelope)(nil), // 2: containerd.types.Envelope
}
var file_github_com_spin_stack_spinbox_api_spinbox_services_vmevents_v1_events_proto_depIdxs = []int32{
	2, // 0: spinbox.services.vmevents.v1.StreamResponse.envelope:type_name -> containerd.types.Envelope
	0, // 1: spinbox.services.vmevents.v1.EventsService.Stream:input_type -> spinbox.services.vmevents.v1.StreamRequest
	1, // 2: spinbox.services.vmevents.v1.EventsService.Stream:output_type -> spinbox.services.vmevents.v1.StreamResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_github_com_spin_stack_spinbox_api_spinbox_services_vmevents_v1_events_proto_init() }
func file_github_com_spin_stack_spinbox_api_spinbox_services_vmevents_v1_events_proto_init() {
	if File_github_com_spin_stack_spinbox_api_spinbox_services_vmevents_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_spin_stack_spinbox_api_spinbox_services_vmevents_v1_events_proto_rawDesc), len(file_github_com_spin_stack_spinbox_api_spinbox_services_vmevents_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_spin_stack_spinbox_api_spinbox_services_vmevents_v1_events_proto_goTypes,
		DependencyIndexes: file_github_com_spin_stack_spinbox_api_spinbox_services_vmevents_v1_events_proto_depIdxs,
		MessageInfos:      file_github_com_spin_stack_spinbox_api_spinbox_services_vmevents_v1_events_proto_msgTypes,
	}.Build()
	File_github_com_spin_stack_spinbox_api_spinbox_services_vmevents_v1_events_proto = out.File
	file_github_com_spin_stack_spinbox_api_spinbox_services_vmevents_v1_events_proto_goTypes = nil
	file_github_com_spin_stack_spinbox_api_spinbox_services_vmevents_v1_events_proto_depIdxs = nil
}
