// Code generated by protoc-gen-go-ttrpc. DO NOT EDIT.
// source: github.com/spin-stack/spinbox/api/spinbox/services/vmevents/v1/events.proto
package vmevents

import (
	context "context"
	ttrpc "github.com/containerd/ttrpc"
)

type TTRPCEventsServiceService interface {
	Stream(context.Context, *StreamRequest, TTRPCEventsService_StreamServer) error
}

type TTRPCEventsService_StreamServer interface {
	Send(*StreamResponse) error
	ttrpc.StreamServer
}

type ttrpceventsserviceStreamServer struct {
	ttrpc.StreamServer
}

func (x *ttrpceventsserviceStreamServer) Send(m *StreamResponse) error {
	return x.StreamServer.SendMsg(m)
}

func RegisterTTRPCEventsServiceService(srv *ttrpc.Server, svc TTRPCEventsServiceService) {
	srv.RegisterService("spinbox.services.vmevents.v1.EventsService", &ttrpc.ServiceDesc{
		Streams: map[string]ttrpc.Stream{
			"Stream": {
				Handler: func(ctx context.Context, stream ttrpc.StreamServer) (interface{}, error) {
					m := new(StreamRequest)
					if err := stream.RecvMsg(m); err != nil {
						return nil, err
					}
					return nil, svc.Stream(ctx, m, &ttrpceventsserviceStreamServer{stream})
				},
				StreamingClient: false,
				StreamingServer: true,
			},
		},
	})
}

type TTRPCEventsServiceClient interface {
	Stream(context.Context, *StreamRequest) (TTRPCEventsService_StreamClient, error)
}

type ttrpceventsserviceClient struct {
	client *ttrpc.Client
}

func NewTTRPCEventsServiceClient(client *ttrpc.Client) TTRPCEventsServiceClient {
	return &ttrpceventsserviceClient{
		client: client,
	}
}

func (c *ttrpceventsserviceClient) Stream(ctx context.Context, req *StreamRequest) (TTRPCEventsService_StreamClient, error) {
	stream, err := c.client.NewStream(ctx, &ttrpc.StreamDesc{
		StreamingClient: false,
		StreamingServer: true,
	}, "spinbox.services.vmevents.v1.EventsService", "Stream", req)
	if err != nil {
		return nil, err
	}
	x := &ttrpceventsserviceStreamClient{stream}
	return x, nil
}

type TTRPCEventsService_StreamClient interface {
	Recv() (*StreamResponse, error)
	ttrpc.ClientStream
}

type ttrpceventsserviceStreamClient struct {
	ttrpc.ClientStream
}

func (x *ttrpceventsserviceStreamClient) Recv() (*StreamResponse, error) {
	m := new(StreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}
